### ISSUE TITLE
Missing config.jelly

### ISSUE THREAD

**Issue by breimers** [thycotic/dsv-jenkins-plugin#1]
[thycotic-vault-jenkins.log](https://github.com/thycotic/dsv-jenkins-plugin/files/6213970/thycotic-vault-jenkins.log)

UI is inaccessible. Missing jelly files cause the failure, see attached logs for details.

**Comment by pmkpa** [comment]
> [thycotic-vault-jenkins.log](https://github.com/thycotic/dsv-jenkins-plugin/files/6213970/thycotic-vault-jenkins.log)
> 
> UI is inaccessible. Missing jelly files cause the failure, see attached logs for details.

I have downloaded and installed jenkins from this link: https://updates.jenkins.io/latest/thycotic-vault.hpi
and i have the same issue. Is there any fix or workaround for this issue?

**Comment by EndlessTrax** [comment]
@pmkpa If you downloaded the plugin from Jenkins, then that is not this plugin. This is the plugin you are looking for- https://github.com/jenkinsci/thycotic-vault-plugin

We are are in the process of uploading this to Jenkins' store and deprecating the old one.

**Comment by breimers** [comment]
@EndlessTrax  I've been hearing that it's "in progress" from thycotic reps over the last two months. Any timeline?

**Comment by EndlessTrax** [comment]
@breimers I have put the request in to Jenkins. So hopefully not long. Days, hopefully?

**Comment by breimers** [comment]
> @breimers I have put the request in to Jenkins. So hopefully not long. Days, hopefully?

Great! My team is ready and waiting to start our integrations, but policy-wise we can only use the published plugins. Hoping this comes soon 👍

**Comment by EndlessTrax** [comment]
@breimers @pmkpa The Jenkins hosting issue seems to be stalled. I found out that the code reviews are done by volunteers. So we just have to wait. Maybe commenting on the issue to tell them you're waiting on this might help this get prioritized a little quicker? 

https://issues.jenkins.io/browse/HOSTING-1106

**Comment by EndlessTrax** [comment]
The plugin is now live in the official Jenkins plugin repo: https://plugins.jenkins.io/thycotic-devops-secrets-vault/
